-- 코드를 입력하세요
SELECT
    USER_ID, 
    NICKNAME, 
    CONCAT_WS(" ", CITY, STREET_ADDRESS1, STREET_ADDRESS2) AS "전체주소", 
    CONCAT(
        SUBSTRING(u.TLNO, 1, 3), '-',
        SUBSTRING(u.TLNO, 4, 4), '-',
        SUBSTRING(u.TLNO, 8)
    ) AS "전화번호"
FROM USED_GOODS_BOARD b INNER JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
GROUP BY 1 HAVING COUNT(u.USER_ID) >= 3
ORDER BY USER_ID DESC