-- 코드를 입력하세요
SELECT
    p.PRODUCT_ID,
    PRODUCT_NAME,
    SUM(AMOUNT * PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT p JOIN FOOD_ORDER o
    ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = '2022' AND MONTH(PRODUCE_DATE) = '05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC