SELECT f.FLAVOR 
FROM FIRST_HALF f LEFT JOIN ICECREAM_INFO i
    ON f.FLAVOR = i.FLAVOR
    AND i.INGREDIENT_TYPE = 'fruit_based'
WHERE f.TOTAL_ORDER > 3000 AND i.INGREDIENT_TYPE IS NOT NULL
ORDER BY f.TOTAL_ORDER DESC;