-- 코드를 입력하세요
SELECT h.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h LEFT JOIN CAR_RENTAL_COMPANY_CAR c 
    ON h.CAR_ID = c.CAR_ID
WHERE c.CAR_TYPE = '세단' AND month(h.START_DATE) = '10' 
GROUP BY CAR_ID
ORDER BY CAR_ID DESC