-- 코드를 입력하세요
SELECT
    CONCAT("/home/grep/src/", b.BOARD_ID, "/", FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD b JOIN USED_GOODS_FILE f
    ON b.BOARD_ID = f.BOARD_ID
WHERE b.BOARD_ID = (
        SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC limit 1
)
ORDER BY FILE_PATH DESC