-- 코드를 입력하세요
SELECT 
    b.BOOK_ID, 
    a.AUTHOR_NAME, 
    CONCAT(year(PUBLISHED_DATE), "-", substring(PUBLISHED_DATE, 6, 2), "-", day(PUBLISHED_DATE)) AS PUBLISHED_DATE 
FROM BOOK b LEFT JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE b.CATEGORY = '경제'
ORDER BY b.PUBLISHED_DATE ASC